BEGIN EXECUTE IMMEDIATE 'DROP TABLE HISTORICO_STATUS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INSCRICOES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE USUARIOS (
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME       VARCHAR2(100)  NOT NULL,
    EMAIL      VARCHAR2(150)  UNIQUE NOT NULL,
    PRIORIDADE NUMBER(1)      DEFAULT 1 CHECK (PRIORIDADE IN (1, 2, 3)),
    SALDO      NUMBER(10, 2)  DEFAULT 0
);

CREATE TABLE INSCRICOES (
    ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID     NUMBER       NOT NULL REFERENCES USUARIOS(ID),
    STATUS         VARCHAR2(20) DEFAULT 'WAITLIST'
                   CHECK (STATUS IN ('CONFIRMADO', 'WAITLIST', 'CANCELADO')),
    DATA_INSCRICAO DATE         DEFAULT SYSDATE
);

CREATE TABLE HISTORICO_STATUS (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSCRICAO_ID     NUMBER        NOT NULL REFERENCES INSCRICOES(ID),
    STATUS_ANTERIOR  VARCHAR2(20),
    STATUS_NOVO      VARCHAR2(20),
    MOTIVO           VARCHAR2(500),
    DATA             TIMESTAMP     DEFAULT SYSTIMESTAMP
);

INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Valentina Rodriguez', 'valentina.rodriguez@fiap.br', 3, 8000);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Sebastian Morales',   'sebastian.morales@fiap.br',   3, 7500);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Camila Herrera',      'camila.herrera@fiap.br',      3, 6800);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Matias Guzman',       'matias.guzman@fiap.br',       3, 6200);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Isabella Vargas',     'isabella.vargas@fiap.br',     3, 5900);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Diego Ramirez',       'diego.ramirez@fiap.br',       2, 2800);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Lucia Fernandez',     'lucia.fernandez@fiap.br',     2, 2600);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Andres Torres',       'andres.torres@fiap.br',       2, 2400);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Gabriela Mendoza',    'gabriela.mendoza@fiap.br',    2, 2200);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Carlos Reyes',        'carlos.reyes@fiap.br',        2, 2000);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Sofia Castro',        'sofia.castro@fiap.br',        2, 1900);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Miguel Lopez',        'miguel.lopez@fiap.br',        1,  600);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Paula Rios',          'paula.rios@fiap.br',          1,  550);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Juan Ortiz',          'juan.ortiz@fiap.br',          1,  500);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Carolina Ruiz',       'carolina.ruiz@fiap.br',       1,  480);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Alejandro Soto',      'alejandro.soto@fiap.br',      1,  420);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Daniela Flores',      'daniela.flores@fiap.br',      1,  380);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Roberto Nunez',       'roberto.nunez@fiap.br',       1,  320);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Natalia Cruz',        'natalia.cruz@fiap.br',        1,  290);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Mariana Pereira',     'mariana.pereira@fiap.br',     1,  230);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Eduardo Silva',       'eduardo.silva@fiap.br',       1,  200);

INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-10 FROM USUARIOS WHERE EMAIL='valentina.rodriguez@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-9  FROM USUARIOS WHERE EMAIL='sebastian.morales@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-8  FROM USUARIOS WHERE EMAIL='camila.herrera@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-7  FROM USUARIOS WHERE EMAIL='matias.guzman@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-6  FROM USUARIOS WHERE EMAIL='isabella.vargas@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-9  FROM USUARIOS WHERE EMAIL='diego.ramirez@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-8  FROM USUARIOS WHERE EMAIL='lucia.fernandez@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-7  FROM USUARIOS WHERE EMAIL='andres.torres@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-5  FROM USUARIOS WHERE EMAIL='gabriela.mendoza@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-4  FROM USUARIOS WHERE EMAIL='carlos.reyes@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-6  FROM USUARIOS WHERE EMAIL='miguel.lopez@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-5  FROM USUARIOS WHERE EMAIL='paula.rios@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-4  FROM USUARIOS WHERE EMAIL='juan.ortiz@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-3  FROM USUARIOS WHERE EMAIL='carolina.ruiz@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 'WAITLIST', SYSDATE-2  FROM USUARIOS WHERE EMAIL='alejandro.soto@fiap.br';

COMMIT;

SELECT i.ID, u.NOME, u.PRIORIDADE, i.STATUS, TO_CHAR(i.DATA_INSCRICAO, 'DD/MM/YYYY') AS DATA_INSCRICAO
FROM   INSCRICOES i
       JOIN USUARIOS u ON u.ID = i.USUARIO_ID
ORDER BY u.PRIORIDADE DESC, i.DATA_INSCRICAO ASC;
