BEGIN EXECUTE IMMEDIATE 'DROP TABLE HISTORICO_STATUS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INSCRICOES CASCADE CONSTRAINTS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE USUARIOS (
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME       VARCHAR2(100) NOT NULL,
    EMAIL      VARCHAR2(150) UNIQUE NOT NULL,
    PRIORIDADE NUMBER(1) DEFAULT 1 CHECK (PRIORIDADE IN (1, 2, 3)),
    SALDO      NUMBER(10,2) DEFAULT 0
);

CREATE TABLE INSCRICOES (
    ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID     NUMBER NOT NULL REFERENCES USUARIOS(ID),
    EVENTO_ID      NUMBER NOT NULL,
    STATUS         VARCHAR2(20) DEFAULT 'WAITLIST'
                   CHECK (STATUS IN ('CONFIRMADO','WAITLIST','CANCELADO')),
    VALOR_PAGO     NUMBER(10,2) DEFAULT 0,
    TIPO           VARCHAR2(20),
    DATA_INSCRICAO DATE DEFAULT SYSDATE
);

CREATE TABLE HISTORICO_STATUS (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSCRICAO_ID  NUMBER NOT NULL REFERENCES INSCRICOES(ID),
    STATUS_ANTES  VARCHAR2(20),
    STATUS_DEPOIS VARCHAR2(20),
    MOTIVO        VARCHAR2(500),
    DATA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP
);

INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Ana Platinum',    'ana.platinum@fiap.br',    3, 5000);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Bruno Platinum',  'bruno.platinum@fiap.br',  3, 4500);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Carla VIP',       'carla.vip@fiap.br',       2, 2000);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Diego VIP',       'diego.vip@fiap.br',       2, 1800);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Eduardo VIP',     'eduardo.vip@fiap.br',     2, 1500);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Fernanda Normal', 'fernanda.normal@fiap.br', 1,  500);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Gabriel Normal',  'gabriel.normal@fiap.br',  1,  300);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Helena Normal',   'helena.normal@fiap.br',   1,  200);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Igor Normal',     'igor.normal@fiap.br',     1,  150);
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO) VALUES ('Julia Normal',    'julia.normal@fiap.br',    1,  100);

INSERT INTO INSCRICOES (USUARIO_ID, EVENTO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 1001, 'WAITLIST', SYSDATE-5 FROM USUARIOS WHERE EMAIL='fernanda.normal@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, EVENTO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 1001, 'WAITLIST', SYSDATE-4 FROM USUARIOS WHERE EMAIL='carla.vip@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, EVENTO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 1001, 'WAITLIST', SYSDATE-3 FROM USUARIOS WHERE EMAIL='gabriel.normal@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, EVENTO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 1001, 'WAITLIST', SYSDATE-6 FROM USUARIOS WHERE EMAIL='ana.platinum@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, EVENTO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 1001, 'WAITLIST', SYSDATE-2 FROM USUARIOS WHERE EMAIL='diego.vip@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, EVENTO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 1001, 'WAITLIST', SYSDATE-7 FROM USUARIOS WHERE EMAIL='bruno.platinum@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, EVENTO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 1001, 'WAITLIST', SYSDATE-1 FROM USUARIOS WHERE EMAIL='helena.normal@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, EVENTO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 1001, 'WAITLIST', SYSDATE-4 FROM USUARIOS WHERE EMAIL='eduardo.vip@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, EVENTO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 1001, 'WAITLIST', SYSDATE-3 FROM USUARIOS WHERE EMAIL='igor.normal@fiap.br';
INSERT INTO INSCRICOES (USUARIO_ID, EVENTO_ID, STATUS, DATA_INSCRICAO) SELECT ID, 1001, 'WAITLIST', SYSDATE-2 FROM USUARIOS WHERE EMAIL='julia.normal@fiap.br';

COMMIT;

SELECT i.ID, u.NOME, u.PRIORIDADE, i.STATUS, TO_CHAR(i.DATA_INSCRICAO,'DD/MM/YYYY') AS DATA
FROM   INSCRICOES i JOIN USUARIOS u ON u.ID = i.USUARIO_ID
WHERE  i.EVENTO_ID = 1001
ORDER BY u.PRIORIDADE DESC, i.DATA_INSCRICAO ASC;